Local Search
zer0-os/ZNS-dapp pull request #25
Opened 2021-03-19 04:28 UTC by Joshua-Jack

Me and Louis got the local search working in the table, we had to merge in the code from figma0.5_nft to get the modal to not pop up.

2021-03-19 20:08 UTC, benefacto requested changes
It would be cool if we could avoid using fixed pixel heights as it will limit responsiveness. Let me know if that's possible.

2021-03-19 20:08 UTC, benefacto commented on src/components/css/nftpage.scss
> +      height: 212px;
Can we avoid using fixed pixel heights?

2021-03-19 20:08 UTC, benefacto commented on src/components/css/nftpage.scss
> +    height: 542px;
Can we avoid using fixed pixel heights?

2021-03-19 20:08 UTC, benefacto commented on src/components/css/nftpage.scss
> +      height: 212px;
Can we avoid using fixed pixel heights?

2021-03-19 20:08 UTC, benefacto commented on src/components/css/nftpage.scss
> +          height: 96px;
Can we avoid using fixed pixel heights?

2021-03-19 20:08 UTC, benefacto commented on src/components/css/nftpage.scss
> +      height: 303px;
Can we avoid using fixed pixel heights?

2021-03-19 20:08 UTC, benefacto commented on src/components/css/nftpage.scss
> +      height: 303px;
Can we avoid using fixed pixel heights?

2021-03-19 20:08 UTC, benefacto commented on src/components/css/nftpage.scss
> +      height: 791px;
Can we avoid using fixed pixel heights?

2021-03-19 20:08 UTC, benefacto commented on src/components/css/nftpage.scss
> +      height: 791px;
Can we avoid using fixed pixel heights?

2021-03-20 02:47 UTC, LPSCRYPT commented
@benefacto I merged in a working branch of the nft page into this branch to get some of the search features working

much of that code for the nft branch has since been changed

we can merge in this code, then I'll pull and merge into my local branch and overwrite the old changes with my newer ones

2021-03-20 04:19 UTC, benefacto commented
> 
> 
> It would be cool if we could avoid using fixed pixel heights as it will limit responsiveness. Let me know if that's realistic or if we should address it later.

This will be addressed in a future pull request.

2021-03-20 04:19 UTC, benefacto approved these changes

2021-03-20 04:19 UTC, merged