Feature/Show WILD price in Ui (Buy Token Redirect Flow)
zer0-os/zNS-dapp pull request #305
Opened 2021-11-24 11:49 UTC by domw30

Link to associated zer0 card:  [Show WILD price in UI](https://zer0.io/a/network/tasks/board/e85a99cf-665f-427c-bb0b-2b4e12ba207a/20b83153-e73a-4aad-bd5e-779edd6b2fe8)

-----

## 1. Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] zer0 card has been moved to the Code Review column
- [ ] zer0 card has a link to this PR
- [ ] A reviewer has been tagged in the zer0 card

## 2. PR type
- [x] Feature

## 3. What is the current behaviour?
- The price ui element and dropdown behaviour does not currently exist in the Title Bar.
- The future button on the title bar currently has conditionals for the text 'Mint'.

## 4. What is the new behaviour?
- Price element added with dropdown behaviour. Dropdown content includes external url links to 'Buy' wild or 'View' wild.
- Future button will only display text 'Mint' to shorten.

## 5. Other information
**Action Required** : The percentage displayed in the UI is currently a placeholder. I wasn't sure if we are able to pull this data from the BE or if a certain API needs to be called for this. - @colbr are you able to provide direction on this, thanks.
**Action Required** : This will require a design review as well. The anchor tags and hover state background colours differ slightly in Figma designs and handover loom video. 
**Action Required** : @colbr are the images okay size wise? I exported them off Figma but seem large.

2021-12-13 01:16 UTC, colbr commented
Hey @domw30 - sorry I haven't been checking review requests, @padala is the currently the person for Marketplace reviews.

Looking good to me so far.

**Re: percentage change**
I believe Coingecko gives you this information through their API. This is the API we're currently calling to get the price. I imagine you'll just need to find where we're currently fetching price, and also stash the percent-change data from the API response.

**Re: image sizes**
Sometimes sizing on Figma exports looks a bit odd because the asset may have been rendered with or without some padding around the Frame. I would open the images in inspector and see the exact size of them, then match them to the exact size in Figma. If they're the same but look different, chuck Figma and Chrome side-by-side and adjust in inspector until it looks right

Few other things:
- Can we remove the grow animation when hovering over the WildPriceContainer? It makes the UI look slightly broken if the WildPriceContainer background animates but the tooltip doesn't.
- Try to use SASS conventions where possible in your `.scss` files - it will keep clutter down. i.e. instead of 
```
.WildPriceContainer {
	...
}

.WildPriceContainer::after {
	...
}
```
Do
```
.WildPriceContainer {
	...

        &::after {
                ...
        }
}
```
etc.

That's my feedback for now, tag @padala as a reviewer when you're finished with the last 2 things 😊

2021-12-22 17:00 UTC, padala commented
@domw30  Let me know once changes from @colbr review are incorporated. Thanks

2022-01-06 19:10 UTC, domw30 commented
@padala, updated this branch with the decimal place format. Now ready for review. Thanks!

I haven't removed the grow on hover as suggested. Removing the grow breaks the flow of the designs - if essential I can remove it now or later date.

2022-01-09 12:50 UTC, padala commented
@domw30  I'll review it today.

2022-01-14 04:02 UTC, colbr requested changes
Looking great @domw30, 2 small changes and it's good to merge! 🔥

Apologies if my previous feedback was a little ambiguous re: grow animation

2022-01-14 04:02 UTC, colbr commented on src/containers/flows/BuyTokenRedirect/BuyTokenRedirect.module.scss
> +	&::after {
I noticed that the `::after` gradient overlay is above the text which changes the white colour, can we set the z-index so the gradient is behind the text and doesn't change the white point?

(colour values below are the main text colours the user sees in current version - both should be #fff)

![Screen Shot 2022-01-14 at 4 59 32 PM](https://user-images.githubusercontent.com/12437916/149449283-5974c5c0-4a0d-46f2-acde-8c56f33c696b.png)

2022-01-15 12:32 UTC, domw30 commented
@colbr mate, updated with the suggestions above. Thanks man!

2022-01-16 03:07 UTC, colbr approved these changes
Nice work @domw30 , looks perfect

2022-01-16 03:14 UTC, merged