Feature : Improve active drop banner behaviour
zer0-os/zNS-dapp pull request #322
Opened 2021-12-07 00:36 UTC by domw30

Link to associated zer0 card:  [Zero Card](https://zer0.io/a/network/tasks/board/e85a99cf-665f-427c-bb0b-2b4e12ba207a/7bc348a8-427a-4aa4-b5e2-0359081bf785)

-----

## 1. Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] zer0 card has been moved to the Code Review column
- [ ] zer0 card has a link to this PR
- [ ] A reviewer has been tagged in the zer0 card

## 2. PR type

Please check the type of change your PR introduces:
- [x] Feature

## 3. What is the current behaviour?
- The banner moves out of view on scroll. 

## 4. What is the new behaviour?
- The banner is fixed when scroll down motion is detected

## 5. Other information

2021-12-07 00:51 UTC, domw30 commented on src/containers/other/PageHeader/PageHeader.module.scss
> +	width: 1234px;
This should be updated to be responsive

2021-12-07 00:52 UTC, domw30 commented on src/containers/other/PageHeader/PageHeader.tsx
> +				<WheelsRaffle />
Are other banners used in place of wheels banner? i.e. is this different to cribs banner

2021-12-07 01:01 UTC, domw30 commented on src/pages/ZNS/ZNS.tsx
> +				<PageHeader
My thinking behind having a PageHeader container here was that the ZNS page file could over time be refactored to look something like:

```
<PageHeader>
    <NavBar />
    <Banner />
</PageHeader>
<PageContent>
    <SomeContent />
    <SomeContent />
</PageContent>
```

2021-12-17 10:54 UTC, padala requested changes

2021-12-17 10:54 UTC, padala commented on src/components/Banners/MessageBanner/MessageBanner.module.scss
> +	color: rgba(255, 255, 255, 1);
Please use scss variables available. If required please add new variables.

2021-12-17 10:54 UTC, padala commented on src/components/WilderIcon/WilderIcon.module.scss
> +	background: linear-gradient(180deg, #1c4358 0%, #2a0047 100%);
Please use scss variables available. If required please add new variables.

2021-12-17 10:54 UTC, padala commented on src/components/WilderIcon/WilderIcon.tsx
> +	const home = () => {
rename it to `redirectToHome` or `navigateToHome`

2021-12-17 12:34 UTC, padala approved these changes

2021-12-17 12:34 UTC, merged