Create MarkdownEditor and MarkdownView components
zer0-os/zNS-dapp pull request #537
Opened 2022-04-27 21:57 UTC by eric-zero-dev

[Associated Notion Card](https://www.notion.so/zerotech/Markdown-components-a2a9a68ec6b5487eac1b4951742e8c6f)

-----

## 1. Pull request checklist

- [ ] Notion card has been moved to the Code Review column
- [ ] Notion card has a link to this PR
- [ ] A reviewer has been assigned to the Notion card

## 2. PR type
 
- [ ] Feature

## 3. What is the old behaviour?

## 4. What is the new behaviour?

## 5. Other information

2022-04-28 19:16 UTC, joonchoi0918 approved these changes
Looks good to me. I have a couple of comments and it will be easy.

2022-04-28 19:16 UTC, joonchoi0918 commented on src/containers/DAO/DAOContainer.tsx
> +			{zna !== DAO_CREATE && zna !== '' && <DAOPage />}
It's hard to read the conditional rendering. Can you update with more readable/understandable conditions? 💪

2022-04-28 19:16 UTC, joonchoi0918 commented on src/containers/DAO/pages/DAOCreate/DAOCreate.tsx
> +			<MarkDownViewer text="Hello World" />
I know it is just example, but can we use longer and more complex markdown text as an example? 💪

2022-04-29 10:44 UTC, colbr requested changes
Looking nice, looks like a pretty handy library! One small filename change request

2022-04-29 10:44 UTC, colbr commented on src/containers/DAO/pages/DAOCreate/DAOCreate.tsx
>  import React from 'react';
Can we change this file to `CreateProposal.tsx`, as the page is for creating a proposal

2022-07-13 03:39 UTC, colbr commented
Closed as this was merged into another branch

2022-07-13 03:39 UTC, closed without merging